# Generated by Django 6.0.3 on 2026-04-12 10:44

import Accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('teacher', 'Teacher'), ('volunteer', 'Volunteer'), ('registrar', 'Registrar')], default='volunteer', max_length=20),
        ),
    ]
