# Generated by Django 6.0.3 on 2026-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBS', '0002_remove_registration_pickup_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('lead_teacher', 'Lead Teacher'), ('assistant_teacher', 'Assistant Teacher'), ('support_staff', 'Support Staff'), ('volunteer', 'Volunteer')], default='volunteer', max_length=30)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('duty_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
